### ISSUE TITLE
Change Child

### ISSUE THREAD

**Issue by Aashutosh3804** [raj457036/shrink_sidemenu_flutter#2]
How to ChildChild when items in menu are clicked

**Comment by YouSour** [comment]
i'm facing this problem too , any idea ?

**Comment by raj457036** [comment]
ChildChild?

If you mean sub-menu items then,

You can use expansion tiles for that purpose Or any custom-made widget of your choice.

**Comment by raj457036** [comment]
closing because of no further information!
